### ISSUE TITLE
No tar files created

### ISSUE THREAD

**Issue by dgiglio** [redguardtoo/elpa-mirror#32]
When I run the `elpamr-create-mirror-for-installed` command, no tar file is created into the destination dir, I only see the `archive-contants`. But I see the tar program operating in the minibuffer.

**Comment by redguardtoo** [comment]
What's your OS?

**Comment by dgiglio** [comment]
Windows 10 and Emacs runs as virtualized AppV application. tar is in the %PATH%

**Comment by redguardtoo** [comment]
What's the output of `tar --version`?

**Comment by dgiglio** [comment]
bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.5.f-ipp

**Comment by pkkm** [comment]
Maybe there are some interesting messages in the `*Messages*` or `*elpa-mirror tar output*` buffers?

**Comment by redguardtoo** [comment]
Have you tried the latest elpa-mirror?

**Comment by pkkm** [comment]
I think I have a good guess for what may be going wrong. `elpa-mirror` runs `cygpath` by going through the shell, and the argument is passed by just wrapping it in double quotes instead of using `shell-quote-argument`. If the path contains some weird special characters, it could be getting modified by the shell, which would result in the wrong path being passed to `cygpath`. But because `shell-command-to-string` ignores errors (i.e. non-zero exit statuses), we wouldn't see the error. Instead, `elpa-mirror` would just pass the error string as a path to `tar`.

I'll submit a pull request that removes this last use of the shell and calls `cygpath` directly from Emacs. I'll also make `elpa-mirror` stop on any error in a command it runs, and I'll replace `elpamr-debug` with a more detailed always-on logging to a background buffer.

**Comment by redguardtoo** [comment]
Please check the latest pull request first.

**Comment by dgiglio** [comment]
It looks like it works now.
